[tool.black]
line-length = 99
target-version = ['py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.venv
  | _build
  | .venv
  | tests-reports
)/
'''

[tool.isort]
profile = "black"
