version: 2.1
aliases:
  - &python_version circleci/python:3.8.3
  - &restore_pip_env
      restore_cache:
        name: Restore pip environment
        key: pip-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}

jobs:
  build:
    docker:
      - image: *python_version
    working_directory: ~/app
    steps:
      - checkout
      - *restore_pip_env
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv ../env
            source ../env/bin/activate
            pip install -r requirements-dev.txt
      - save_cache:
          key: pip-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
              - ../env
  
  code_quality_checks:
    docker:
      - image: *python_version
    working_directory: ~/app
    steps:
      - checkout
      - *restore_pip_env
      - run:
          name: Run code quality checks
          command: |
            source ../env/bin/activate
            ls -la
            make checks

  run_tests:
    docker:
      - image: *python_version
    working_directory: ~/app
    steps:
      - checkout
      - *restore_pip_env
      - run:
          name: Run code quality checks
          command: |
            source ../env/bin/activate
            make pytest

workflows:
  version: 2
  validate_pr:
    jobs:
      - build
      - code_quality_checks:
          requires:
            - build
      - run_tests:
          requires:
            - code_quality_checks
